### ISSUE TITLE
NSAssert after series of "git mv"

### ISSUE THREAD

**Issue by vng** [gitx/gitx#106]
- Build latest master
- Open any repository
- Make series of "git mv" commands for any files and folders
- NSAssert1 in PBGitIndex.m, (NSMutableDictionary *)dictionaryForLines:(NSArray *)lines

_lines_ contains last non-paired element with some numeric value ("10" in my case)
git version 2.15.1

**Comment by vng** [comment]
Moreover, if you have more than 30 files in modified, deleted or created, "Unstaged changes" list view becomes bugging. It doesn't show more changes until stage some of them ... Seems like this bug is connected with topic's header NSAssert.

**Comment by tiennou** [comment]
Well, #106 is not #102, sorry about that @vng. Your 2nd comment is the 2nd part of #102, but I have seen the first one too, and IIRC it's related sometimes ending up with incorrectly ordered data/calls when refreshing the index (I know it's easy to get a confused representation). I'll try to investigate what happens when `git mv` things around.

**Comment by vng** [comment]
Good. At least your #9a69e976684f79a1ad812c937d585028ab29f404 fix makes master more robust.
And your solution is definitely better than mine.
