### ISSUE TITLE
Bug: "unrecognized selector sent to instance"

### ISSUE THREAD

**Issue by apepper** [gitx/gitx#12]
When opening `gitx` using the command line tool, I'll get the following error:
```
> gitx
2017-01-02 11:07:13.708 gitx[10452:449267] -[GitXApplication open:withOptions:]: unrecognized selector sent to instance 0x7feec8d70df0
2017-01-02 11:07:13.710 gitx[10452:449267] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GitXApplication open:withOptions:]: unrecognized selector sent to instance 0x7feec8d70df0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff85b0b452 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff856a3f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff85b7510d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff85a7b4d1 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff85a7b058 _CF_forwarding_prep_0 + 120
	5   gitx                                0x0000000103e8fc6e handleOpenRepository + 119
	6   gitx                                0x0000000103e90c17 main + 534
	7   libdyld.dylib                       0x00007fff925385ad start + 1
	8   ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    10452 abort      gitx
```

`gitx` is a alias for `/Applications/GitX.app/Contents/Resources/gitx`. `/Applications/GitX.app`is the latest compiled `master` from https://github.com/gitx/gitx (currently 40d95be0c99999580e1e741ac5fe90df3f77a214). I'm running OSX 10.11.6 (El Capitain).

If GitX is already running with an open window, then the command does _not_ crash.

**Comment by ssp** [comment]
@apepper: I am afraid, I cannote reproduce the issue (running 10.12.2, though).

At least on my machine GitX installed the gitx binary at /usr/local/bin/gitx. Just to ensure we don’t get off-track because of unexpected files, can you confirm that your alias is working as you expect and there’s nothing else getting in the way? (Perhaps running `mdfind "kMDItemFSName == 'gitx' && kMDItemContentType == 'public.unix-executable'"` gives an overview of all the potentially relevant files?)

Reading the location of the code that crashes:

```
    GitXApplication *gitXApp = [SBApplication applicationWithBundleIdentifier:kGitXBundleIdentifier];
    [gitXApp activate];
    [gitXApp open:repositoryURL withOptions:arguments];
```

I would expect the gitx command to launch GitX before running into the problem. Does that happen? 

If not: could it be that there is an old copy of GitX somewhere on your system that gitx tries to launch? If so, it may be interesting to see which copy of gitx AppleScript opens, e.g. when running `osascript -e 'tell app id "net.phere.GitX" to activate'`.

**Comment by apepper** [comment]
Thank you for your help @ssp. With your pointers I was able to solve the problem.

There was indeed an outdated version of `GitX` lying around. So `osascript -e 'tell app id "net.phere.GitX" to activate'` opened the old version of `GitX`, which was located in `~/Library/Application Support/GitX/`. I don't know, how it got there, but the outdated version was `0.15.1962 dev` from 2014. Maybe an old installer put it there. After I deleted `~/Library/Application Support/GitX/` the `gitx` command worked as expected.

I found the outdated `GitX` using `mdfind "kMDItemFSName == 'GitX'"`.
