### ISSUE TITLE
Contextual menu items don't work on stashes

### ISSUE THREAD

**Issue by ksuther** [gitx/gitx#121]
This seems to be new after develop got merged to master.

Steps to reproduce:

- Select a stash in the sidebar
- Right-click on a stash and try to drop it
- Nothing happens

It looks like PBRefMenuItem is creating the menu items with actions but the target is nil. The problem then is that PBGitHistoryController isn't in the responder chain, so the action isn't called.

**Comment by tiennou** [comment]
Fixed with recent master [changes](a92319c9cb9d4ae4651f062a2dce740d290a8dc9). I finally see the light at the end of the responder tunnel ✨.

There's quite a bit of testing to be done, mainly around things that use remotes. I think I fixed fetch, but I only skimmed the push/pull code, so it might not behave as consistently…
