### ISSUE TITLE
Graph seemingly disconnected when it shouldn't be

### ISSUE THREAD

**Issue by claybridges** [gitx/gitx#17]
I start in this state:

![unknown](https://cloud.githubusercontent.com/assets/96004/21955913/d0819d92-da42-11e6-80bd-637335877f9b.png)

When I `git checkout 1d4e8c1`, GitX suddenly shows me in a strange disconnected state:

![unknown2](https://cloud.githubusercontent.com/assets/96004/21955940/62f15e56-da43-11e6-8117-ac6cbc75f5cd.png)

This is built against commit SHA `8b1aa1562504d182130e94f31dda2ee07d10a649`. I'd be happy to step in Xcode and test out theories against this repo, if you have any.

**Comment by tiennou** [comment]
I've seen it happen too. I think it's caused a rebase (which changes commit-dates), which I think confuses our lane-builder. I've also seen a degenerate case where (in your example) you'd get only the 3 leftmost-lane commits, and the rest would be gone, but I think it's when the branch is filtered.

**Comment by turbolent** [comment]
Bisecting it, it looks like it's broken since 71b598b

**Comment by tiennou** [comment]
That 71b598b commit is me trying to fix some other issue there was with the code "the other way around". It seems this instance of the bug can be traced back to the switch to `libgit2`, because it can order commits differently than what `git` does, and the lane-wrangling code sometimes doesn't like it.

IIRC I was trying to fix an issue where sometime, the topological sort starts with unrelated, old branches instead of recently-changed ones, which makes for a messy graph. Having it time-sorted fix that issues, but it can confuse the lane grapher, hence *this* issue.

See #19 for a (WIP) tentative fix.
