### ISSUE TITLE
Commit message font has changed

### ISSUE THREAD

**Issue by claytonrcarter** [gitx/gitx#173]
It looks like commit a1184707 changed how the font for the commit message box is set. At least for me, this broke something and I'm now getting a variable width font in the commit message box. I'm on 10.13.6 built as of 6c43b53d with Xcode 10.1 

![screen shot 2018-12-13 at 10 54 48 am](https://user-images.githubusercontent.com/1420419/49950297-8c42ca80-fec5-11e8-8565-fc258cf214bb.png)

**Comment by tiennou** [comment]
That's strange, because (as I should have described in a118470), I had to change that code because setting the attributes loses the "magic" auto-darkmode text color. Here's my equivalent 10.14 screenshot (but I'm not sure what build it comes from):
![capture d ecran 2018-12-21 16 52 20](https://user-images.githubusercontent.com/81099/50350959-fcde8c80-0540-11e9-9af4-b11c7dd1a6eb.png)

I suppose reverting fixes it ?

**Comment by claytonrcarter** [comment]
Yes, I just checked and after reverting a118470, the font is back to monospace.

**Comment by goneng** [comment]
I have the same problem - using Xcode 10.1 (10B61) on macOS High Sierra 10.13.6 (17G4015).
