### ISSUE TITLE
Who are the maintainers?

### ISSUE THREAD

**Issue by jspiro** [gitx/gitx#205]
It's nice that this important project has its own org at gitx/gitx on GitHub to make it easy to find (it's not easy to find with Google or GitHub, ironically), but it's not getting any love from whomever created that.

There are 14 PRs open, most passing checks, 50 issues. Lots of activity for a decade old codebase, yet little recent activity from the maintainers. How can we reclaim this project other than adding the 675th fork?

**Comment by hannesa2** [comment]
I agree !
Who ever has the power to enable maintainers, please add one (or more) person to the maintainer list, to avoid a dead project

**Comment by hannesa2** [comment]
Some candidates are the persons who made recent pull requests

**Comment by jspiro** [comment]
Is there a petitioning process with GitHub? What do the do if an important maintainer disappears?

**Comment by hannesa2** [comment]
Sadly this is the future of a lot of Github projects, the maintainer disappears and project dies slowly. 
There is no relay race culture for that.

There are several strategies to handle this, but all depend on current owner
* give someone else the ownership (triggered **once** by owner)
* add someone to the maintainer, but `settings` tab can be only reached by owner (triggered **always** by owner)
* fork repo and continue there. (triggered by someone else) But this add more confusion which is the current repo and the current repo name is too good

That's why is always good to have more then one maintainer. I hope the maintainer will read this.

**Comment by hannesa2** [comment]
@jspiro

Btw I started (and I'm not finished) to build a arm app for Apple Silicon, but with the usage of a lot git submodules it's a cascading huge load task.

And almost every submodule has the same maintainer question

**Comment by jspiro** [comment]
Alright, I'm taking a stand. It's time to fork one final time. There's too much promise in this simple but powerful tool. Too many hours of unrequited community development.

Let's continue the conversation here: https://github.com/gitx-community/gitx/discussions/4

**Comment by Vincent-Nikkelen-mkb** [comment]
Hi,

I am happy to see you are willing to take over this gem of a project. Been using it since January 2013, but believe this is the first time I speak openly.

Life changes; job, family, other interests or health might interfere with what you were and want to do. Sometimes you loose interest or think the burden is too high. One makes choices and especially in open source we need to respect those. But there is always that wish to continue, the hope you will have more time for it in the future or get the help you need.

Asking if a project is maintained and then publicly forking it withing 24 hours is a hasty action in my opinion. It might alienate the current maintainers who have put a lot of work into this in the past and definitely have made plan for the future.

Please give the 'old' maintainers some time to react. Maybe they want to discuss this among themselves first before reacting publicly or they just need time to realize it is time to hand over the control.

I have seen too many hasty forks die in their early stages. The one forking is loosing interests, realizing it is more work than expected or simply has gotten out of the fork what was needed.

Please allow the current maintainers to react, see if they are interested to add you to the team. Your energy might activate theirs.

Success of this project is better served in this repository which people know, trust and where a lot of knowledge hangs around.

Again, really happy to see your engagement, but for the sake of the project I hope there is a middle way. Forking should be the last option.

**Comment by jspiro** [comment]
Hey Vincent, I appreciate you're thoughtful note.

I've been following this repo for probably years now. Hard to recollect when forks start, but I've been building it locally for years as well, ever since the early days when updates stopped working and there were competing forms.

While you're right, my actions are hasty at face value, I've been patiently waiting for updates like so many others. PRs stretching back 4+ years. I channeled my frustration into action because I love this tool so much and couldn't be productive without it. Life can get in the way, and maybe a challenge like mine wakes you up, that's to be seen.

I'd like to provide a home for this that is collaborative and active. I hate forks, and actually it was hard to even remember this one as obvious as it is. Github search couldn't even find it despite my stars for it. I had to check the git config on my local clone to remember. It's a sad demise of a promising fork, while we have PRs trying to build it for M1 chips wasting away,

I don't want to be a maintainer of gitx/gitx, I want there to be an active group that cannot stagnate because life gets in the way for one or even half of us. That's what I'm offering. If the old owners want that too, I'm game. Otherwise, please join me at what I otherwise hope is the final fork.

**Comment by ADTC** [comment]
I'm just thinking out loud here, that the people of `gitx` organization should be able to help add more people to the organization, who in turn can add more maintainers: https://github.com/orgs/gitx/people

@claybridges or @nanoant can you help please?
