### ISSUE TITLE
MacOS Ventura (13.x) dark mode, some menu text needs color fix

### ISSUE THREAD

**Issue by virajkanwade** [gitx/gitx#356]
<img width="764" alt="Screenshot 2022-11-21 at 10 01 49 AM" src="https://user-images.githubusercontent.com/316111/203127692-a35ee7c4-a5a8-4a34-bbd7-93cc86775f3c.png">

**Comment by virajkanwade** [comment]
The 'Source', 'Blame' and 'History' menu is hard to read

**Comment by hannesa2** [comment]
Thanks for your report. We also need some helping hands with pull request

**Comment by virajkanwade** [comment]
@hannesa2 would have loved to help, but its been 10 years since I have touched ObjC :(

**Comment by ADTC** [comment]
I couldn't find this by searching for "Tree View" or tree mode so here it is in a comment. I concur that the Source file list and blame are still light. History is dark, but the bar above is light (with white fonts).

**Comment by ADTC** [comment]
@hannesa2 I have the pull request with a nice dark theme :)

Unfortunately the bar will have to be fixed in the submodule https://github.com/gitx/MGScopeBar project. I haven't figured out how, and ObjC isn't something I'm familiar with. Hope someone with ObjC experience can help fix the bar itself. (But I may hack something up to see if I can make it work.)

**Comment by ADTC** [comment]
Oh no, @hannesa2 I just got some free time and started looking into this. I think we should remove `MGScopeBar` and replace it with `PBGitGradientBarView` instead. We already use this for the bar with buttons for `All` `Local` and the search box. It works correctly with Light vs. Dark mode changes and looks almost the same as `MGScopeBar`.

Thanks for the merge though. I'll just make the above into another PR (if I can get it working).
