### ISSUE TITLE
Build & distribution system

### ISSUE THREAD

**Issue by claybridges** [gitx/gitx#38]
We'd benefit from having a system for push-button build and binary distribution.

**Comment by tiennou** [comment]
I'm on it, I just need to find some time to redo the Travis setup I made in my fork and document it.

**Comment by tiennou** [comment]
Okay, Travis is go now. For the record, its running under the authority of my own account (because lazyness).

I'll ponder the distribution problem a little more, but right now it is thus :

- Using GitHub Releases from Travis works, but you have to tag your release beforehand.
- There are a few ways of generating an appcast.xml directly from Github Pages, but right now our repository already has a gh-pages branch (with unknown contents to me, haven't checked yet), and we also have a Site directory with another version of someone's else pages (@pieter maybe ? it seems pretty old). Add the gitx.github.io repo to that, and I don't know what's going on here anymore 😉.
- Travis cannot easily commit back changes, so I don't think it can trigger a Page rebuild on its own.
- I haven't got near Sparkle yet (apart from updating our submodule to the current version). I think I need some key for signing the release 😢.
- Also, we might want to sign releases, which means go to Apple for a Dev ID.

So, if someone has a better idea, I'm open to suggestions.

**Comment by whitecat** [comment]
Does binary distribution mean something that is already compiled and ready to use on mac?

**Comment by andreif** [comment]
@whitecat Yeah, that's how I see it, `dmg`-files to be published on homepage/GitHub-releases.

**Comment by whitecat** [comment]
Can Travis auto run your build instructions from this website https://github.com/gitx/gitx/wiki/Build-instructions?

**Comment by whitecat** [comment]
To get a Dev ID would you want the app be an individual account or a company one?

**Comment by tiennou** [comment]
Travis can, and is mostly setup now. We just haven't turned on The Switch yet, because there's no automatic update mechanism (i.e. we need to setup a Sparkle feed).

The second point is a good one. Bluntly, I don't want to go through the hassle of building a company just for some certificates. I *might* register as a dev just for that, but I also might not 😉.

**Comment by whitecat** [comment]
Sadly you have to pay $100 a year and I do not think people will donate enough to make up that cost.

**Comment by tiennou** [comment]
I have found a way to make automated releases (I think, there are many things I'm not sure of but *in theory* it should work).

As stated earlier, we can use Travis <=> GitHub Releases integration to perform the deployment step. Then it's possible to generate an appcast.xml file from that, using the release metadata kindly provided by Jekyll.

A big caveat is that we might need to kill the `gitx.github.io` repository (actually, now that I think about it some more, that's not true, but I digress). Yesterday, I pushed an updated gh-pages branch with a "prototype" appcast, which is now online [here](https://gitx.github.io/gitx/appcast.xml), under the gitx/gitx repo gh-pages [branch](https://gitx.github.io/gitx), under the gitx.github.io [repo](https:/gitx.github.io) (yeah it's confusing, hence my point about killing the other one).

Another option would be to keep it that way, just keeping what's required by the appcast.xml, which would give us https://gitx.github.io/gitx/appcast.xml as the Sparkle feed URL (that gitx path is hardcoded).

So the release process would be this :
- Execute a script (eg. `Scripts/release.py`), which would perform the "version update dance", commit it, and tag it.
- Push the changes.
- Travis would faithfully register that there's a tag, so would build and execute `Scripts/deploy.py`. This would cause our beloved "build artifact" (:wink:) to be packaged in a DMG, and published as a GitHub Release.
- GitHub Pages *should* update the appcast.xml. I'm not sure if merely pushing a release would do the trick or if it requires prodding it. I think the latter can be expected, but I haven't checked yet. And this actually can give us time to *ACTUALLY TEST THAT THE BUILD WORKS*, and setup a nice changelog for Sparkle consumption (which could also be automated in some way).

Is everyone on board with that ? As always, comments and suggestions are more than welcome.

**Comment by tiennou** [comment]
Meantime, I'll be working on that bunch of scripts. Relatedly, are you guys more Pythonistas than Rubyists ? I'm not that well versed in Python, so my vote naturally goes toward Ruby...

**Comment by nanotech** [comment]
Using the gh-pages branch on gitx/gitx is fine, and keeps it together in the same repo.

The [Jekyll/Appcast tool Glow][0] exists if that would be useful directly or as a reference.

If adding a release doesn't trigger a Pages rebuild, there's a [build request API][1] now that could be called from Travis. For testing builds before general release, maybe have a whitelist that needs to be edited before versions appear in the appcast?

If we write a high-level changelog that isn't just the Git history, that should probably be finished before tagging the release. Including changelog entries as part of feature and bugfix PRs would be a good way of distributing the effort.

The scripts would probably be short enough for the language not to matter too much, so I'd say use what you're familiar with. (I like Ruby myself.)

For the Sparkle DSA signing key, I think it would be a good idea to have a few people (at least @tiennou and @ssp) keep copies of the private key to ensure continuity of update signing in the long-term. Documenting how the keys are managed would be good too. (e.g. stored in Travis, sent to key holders PGP-encrypted, stored encrypted in cold storage.)

[0]: https://github.com/DangerCove/Glow
[1]: https://developer.github.com/v3/repos/pages/#request-a-page-build

**Comment by andreif** [comment]
Use the language which is more convenient to develop with than to use, so you can keep a good velocity. I would personally prefer Python due to easier debugging but if you are more productive with Ruby then sure use it, so we get things done faster.

**Comment by pvinis** [comment]
isn't Travis free for open source? 

also, you can look into fastlane. it's basically using ruby and has some helpers. I can help with that too. it's nice fire doing builds.

**Comment by andreif** [comment]
@pvinis Travis is free, but you need to pay  💰 in order to be able to sign binaries and release to App Store. Otherwise users have to change macOS settings to allow downloaded binaries from unknown developers if I am not mistaken.

Oh, I forgot about fastlane! Sure use it and switch all scripts to Ruby for simplicity.

**Comment by pvinis** [comment]
ah you mean apple, for dev. well, i pay for mine already, so i guess we can either do it so that someone that already pays, he also signs gitx, or we can have some people donate. i mean, 100 per year is like 1 per year per user if there are 100 users. and im sure there are more than that.

ps. are there any analytics actually for gitx?

**Comment by tiennou** [comment]
Fastlane looks iOS only though.

@pvinis As far as I know, there are none. We might want to have that sometime, but right now the priority is releases. And I think Sparkle covers that too.

**Comment by andreif** [comment]
@tiennou https://github.com/fastlane/fastlane/issues/274

**Comment by felixyz** [comment]
I've been a GitX user since the early days (even made [a microscopic contribution](https://github.com/gitx/gitx/commit/d77d85b)) and will _gladly_ donate some money towards getting the release pipeline up and running, if someone sets up a means for doing so. I would like it if GitX could gain more traction again.

It's probably been a year or two since I updated the app—as someone else said it's amazing how well it's stood the test of time. Just built the latest from master, great feeling to have a brand new version running after such a long time! Many thanks to everyone who has kept this project alive!

**Comment by pvinis** [comment]
i will look into either gitlab-ci or some free circle ci instance or something. there must be something free/self-hosted for this.

then we can use sparkle for updates and host the appcast on the repo, or the repo pages.

for signing, like i said before, we should either just use one of ours, or just people must allow it specifically.

**Comment by mangerlahn** [comment]
Is there any chance we can get our hands on http://gitx.frim.nl? Does anybody know him? It would be nice to have at least the original app cast point to the new one to move all users over. 

#5 discussed the name, but it seems that no final decision has been made. 
So do we plan to publish this as a new app (GitX(N)) or as an update to the existing one (GitX). Version numbering is another thing to consider. Would that be 0.8 or the 1.0?

**Comment by rjmunro** [comment]
@pvinis Travis has Mac OS instances, even on the free travis.org service. There have been issues recently with the queue taking a long time to start, but it generally works well.

**Comment by pvinis** [comment]
i asked pieter https://twitter.com/pvinis/status/924311517922816000 here and he said he would like to help. so i think if we know exactly what we need, then we can ask him for specific things. basically the signing for distribution and the website for sparkle updates are the important things, right? is there something else?

**Comment by apepper** [comment]
Any news on this? I would really much appreciate prebuilt versions of gitx.

**Comment by aterenin** [comment]
Any further updates? I've been using a prebuilt version someone uploaded to one of the GitHub issues. GitX is still the best Git GUI out there IMHO - UI/UX is near-perfect for essentially anyone without an ultra-heavyweight use case better handled on command line anyway. 

A publicly-released binary would be a big plus, even if it isn't signed and users have to click through System Preferences to open it. Most Git users are savvy enough to know how to do that anyway.

**Comment by AntonNguyen** [comment]
> GitX is still the best Git GUI out there IMHO - UI/UX is near-perfect for essentially anyone without an ultra-heavyweight use case better handled on command line anyway.

I got tired of waiting for an update to gitx, so I started looking for alternative. _Most_ of them didn't have that key `amend` feature that I love within gitx. That's until I found [fork.dev](https://fork.dev/). It's under active development, has a ui _similar_ to gitx, and has cool new tricks like tabs.

**Comment by plan44** [comment]
thanks for that hint. fork.dev really feels like gitx reborn! I only hope the two devs who do this now in their spare time don't get exhausted before they find a business model or decide to OS it ;-)

**Comment by tiennou** [comment]
Thanks for the hint as well, I'll be sure to take a look soon 🤣.

**Comment by aterenin** [comment]
Not to be a snob, but that app isn't open-source, and their logo risks making me hungry in the middle of the day. As far as I can tell, GitX still largely works, as long as one can get it to build on a modern system. What's the issue with creating a release - is something still broken?

**Comment by tiennou** [comment]
The main, underlying issue is that, I'm neither a "modern", or a "professional" ~System 7~ ~MacOS 8~ macOS developer, and this is Open-Source 😜.

More seriously, the underlying issue has a "big picture" description at https://github.com/libgit2/objective-git/issues/648. The TL;DR is that the homemade 4-arch builds of OpenSSL, needed to get SSH support, is broken on Travis. There has been some work on that front as part of Objective-Git (w.r.t to brewed dependencies mostly, but GitX brings a bunch of signing issues on top of that, and this ends up with stacked build systems, which is never fun to fix on Travis).

I could do a release, but since I'm not in a position to invest time into it… I usually have a tendency to post "private" developer builds from Xcode, when there's a few issues closing, but the actual `publish.py` that does the checking/tagging/building/publishing hits codesigning failures since Mojave, while it's working in Xcode itself.

Sorry to vent off like this. It's been somewhat frustrating to not be able to do more releases because OS updates happen to have broken a workflow 😉.

**Comment by aterenin** [comment]
Hey, let me just take a moment here that the effort you've put into keeping GitX alive over the past few years is highly and strongly appreciated! 😀😀 

From a quick look at the that page, sounds like quite the issue.

There's something to be said for simply manually tagging a commit, uploading a pre-built binary to the repo by hand, calling it a pre-release in the meantime - at least until the OpenSSL issues are addressed. That way people who develop for platforms other than Mac OS / iOS and who do not have Xcode installed can at least get a binary.

**Comment by pioug** [comment]
Found out today that I was using version of GitX from 2014 😆 So I tried to build a binary from Travis and upload it to GitHub as a release. I just followed the build instructions:

Commit: https://github.com/pioug/gitx/commit/002a20f33532d07b31714eb080f0ef7d41dfe7c6 
Job: https://travis-ci.com/github/pioug/gitx/builds/155135323
GitHub release: https://github.com/pioug/gitx/releases/tag/v0
Build archive: https://github.com/pioug/gitx/releases/download/v0/build.zip

I can't tell if the OpenSSL issue is fixed now, I don't know anything about Xcode and MacOS development but I would be happy to help on CI part if that's what you want to achieve. 

@tiennou @nanoant @claybridges

GitX is so good 💕 but finding this maintained version plus the binary was a long journey for me 😅 As a web dev I can also help to update http://gitx.github.io/ if needed.

**Comment by Feuermurmel** [comment]
I think now is the time I would like to weigh in on this issue.

First of all, I'm really glad that this app exists. I've tried so many Git GUI apps, paid and free, closed and open-source, and most of them are overloaded with features I don't need or rather use the command line for. GitX really does exactly what I want. On Linux, I mostly use _Git Cola_ and _gitk_, they do their resepective jobs well but don't really fit into a macOS environment.

I've also seen people I've taught Git struggle with the toolset built e.g. into IDEs like IntelliJ IDEA and VS Code and when I showed them GitX they immediately said "oh, wow, that looks much easier to use!"

I've been using _GitX 0.15.1964 dev © Pieter de Bie, 2010_ for the past 10 years, fearing that some macOS upgrade or something else will eventually break it. That is, until I found out that a new team has taken over maintaining and improving it in the meantime!

I'm currently using [0.16.2327 dev](https://github.com/gitx/gitx/releases/tag/build%2F0.16%2F2327) from 2018, the newest version available on the _Releases_ page. It's a bit buggy and there are some small things I'd be glad seeing fixed, but I still like using it.

Now seeing all of this, I think it's a real shame that the work that has been done in the meantime is not available to most people running GitX. I've inversted an hour or so and wasn't able to produce a working build on my machine. I would certainly not expect a friend I just started teaching Git and some coding basics to be able to produce a build on their own. But we both certainly benefit from the app existing in its current shape!

I see that a lot, possibly annoying work might be necessary to get the current code-base into a shape to again be able to produce regular release builds. Having a fully automated setup for this is ceratinly desired and time well invested. But if this desire to get this release process to work as well as possible is standing in the way of getting any release published at all, then I'm viewing this as effort being wasted.

I can't make a suggestion as to what course of action would be the best even in my oppinion, I don't know what the real hurdles are right now. What I can do, is tell you that I, as a simple user of GitX, would like to see that the continued work on this project is available to users in _any form_. Even if it means that someone had to produce a build manually in a convoluted way, producing an unisgned binary, rather than seeing the effort being wasted because it's inaccessible to most users.

This is my honest oppinion. I hope I haven't stepped on anyones toes and would like to restate that I'm glad to see all the effort being put into this project, any effort whatsoever. I'm happy for having been able to use this app for so long.

:)

**Comment by claytonrcarter** [comment]
FYI, as of yesterday, pre-built binaries are now available for all pushes to PRs and master, and we now have automated released based on GitHub releases and tags. See #255 #256 #258 and https://github.com/gitx/gitx/releases/tag/0.17

They aren't signed and they don't plug in to Sparkle updates, but they're something.

**Comment by hannesa2** [comment]
I guess it's obsolete now, because we can build x86_64 and arm64.
Please reopen if it's still an issue
