### ISSUE TITLE
Where can I find an up to date build?

### ISSUE THREAD

**Issue by justincbeck** [gitx/gitx#455]
Last build that's tagged is from April of 2023. Does the build process not create a build any more?

**Comment by hannesa2** [comment]
Unfortunately there were no significant improvements in the meantime which could cause a new release. 
Last merge built with artifacts https://github.com/gitx/gitx/actions/runs/10352681392

I only made the pipeline, because with objective C I'm naked at all, but I'll merge any pull request wich makes somehow sense.
