### ISSUE TITLE
Changing deployment target from 10.9

### ISSUE THREAD

**Issue by ksuther** [gitx/gitx#93]
The current deployment target is 10.9. Considering it's unlikely for developers to be on an older system, is there any reason we shouldn't move it up to something newer (such as 10.11)?

**Comment by mangerlahn** [comment]
I agree on this, as it makes development a lot easier. There are quite some modernised APIs (especially on the UI side), which are introduced in newer releases. It would really make it hard to reimplement changes on older platforms.

**Comment by gpongelli** [comment]
I've just tried to build this new GitX, I think it's better to set 10.12 as deployment target.
Trying to follow default building instruction, the GitX build gives me around 200 like this
`ld: warning: object file (External/libgit2.a(annotated_commit.c.o)) was built for newer OSX version (10.12) than being linked (10.8)`

My 2 cents.
Thank you.

**Comment by tiennou** [comment]
I was recently considering doing that, because 10.10 has the nicer NSViewController. Maybe 10.11 could be the sweet spot though… But I have no hard numbers to back up any change, so for the sake of doing polls, my current OS is 10.12 😉.

@gpongelli that's because of Homebrew, which defaults to the current system version (you can't fix everyone's packaging problems and get it right every time 😉).

**Comment by ksuther** [comment]
I'd suggest 10.11 at a minimum. We're under 1% usage for 10.10, and 10.11 is under 6%.

**Comment by hannesa2** [comment]
We are on `10.11` now. Please reopen, if there is an additional action required
